[workspace]
members = ["subgraph","manager"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }
async-graphql = "7.0.17"
async-graphql-axum = "7.0.17"
axum = "0.8.4"
tower-http = { version = "0.6.6", features = ["cors"] }
