version: '1'

dev_mode: true
playground_enabled: true

graph:
  token: ""

execution_config:
  file:
    path: execution-config.json
    watch: true

cors:
  allow_origins:
    - "*"
  allow_methods:
    - GET
    - POST
    - OPTIONS
  allow_headers:
    - "*"

events:
  providers:
    nats:
      - id: default
        url: nats://127.0.0.1:4222
