directive @edfs__natsRequest(
  subject: String!
  providerId: String! = "default"
) on FIELD_DEFINITION
directive @edfs__natsPublish(
  subject: String!
  providerId: String! = "default"
) on FIELD_DEFINITION
directive @edfs__natsSubscribe(
  subjects: [String!]!
  providerId: String! = "default"
  streamConfiguration: edfs__NatsStreamConfiguration
) on FIELD_DEFINITION

input edfs__NatsStreamConfiguration {
  consumerInactiveThreshold: Int! = 30
  consumerName: String!
  streamName: String!
}

type Subgraph @key(fields: "id", resolvable: false) {
  id: ID! @external
}

type Subscription {
  FameOnValueChange: Subgraph!
    @edfs__natsSubscribe(
      subjects: ["gema.fame.value.updated"]
      streamConfiguration: {
        streamName: "demoStream"
        consumerName: "edg_subgraphs"
        consumerInactiveThreshold: 30
      }
    )
  JimOnValueChange: Subgraph!
    @edfs__natsSubscribe(
      subjects: ["gema.jim.value.updated"]
      streamConfiguration: {
        streamName: "demoStream"
        consumerName: "edg_subgraphs"
        consumerInactiveThreshold: 30
      }
    )
  ZorusOnValueChange: Subgraph!
    @edfs__natsSubscribe(
      subjects: ["gema.zorus.value.updated"]
      streamConfiguration: {
        streamName: "demoStream"
        consumerName: "edg_subgraphs"
        consumerInactiveThreshold: 30
      }
    )
}
