[package]
name = "manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { workspace = true }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
